images:
  web:
    version: "1.8.0"
  init:
    version: "1.2.1"
  sync:
    version: "2.0.1"
  exporter:
    version: "1.4.2"
  redis:
    version: "8.4.0"
  blackbox:
    version: "0.28.0"

resources:
  web:
    replicas: 2
    storage: 10Gi
    cpu: 135m
    memory: 800Mi

  collaboration:
    cpu: 135m
    memory: 800Mi

  redis:
    storage: 2Gi
    cpu: 10m
    memory: 100Mi

  sync:
    cpu: 50m
    memory: 64Mi

  init:
    cpu: 50m
    memory: 64Mi

  exporter:
    cpu: 10m
    memory: 100Mi

  database:
    storage: 10Gi
    replicas: 3
    cpu: 200m
    memory: 512Mi

  blackbox:
    cpu: 50m
    memory: 128Mi
