images:
  web:
    version: "1.9.2"
  init:
    version: "1.2.1"
  sync:
    version: "2.0.1"
  exporter:
    version: "1.4.2"
  redis:
    version: "8.4.0"
  blackbox:
    version: "0.28.0"

resources:
  web:
    replicas: 1
    storage: 5Gi
    cpu: 295m
    memory: 750Mi

  collaboration:
    cpu: 295m
    memory: 750Mi

  redis:
    storage: 1Gi
    cpu: 10m
    memory: 100Mi

  sync:
    cpu: 25m
    memory: 128Mi

  init:
    cpu: 25m
    memory: 128Mi

  exporter:
    cpu: 5m
    memory: 64Mi

  database:
    storage: 10Gi
    replicas: 2
    cpu: 100m
    memory: 512Mi

  blackbox:
    cpu: 25m
    memory: 128Mi
